title: "Shey Jean-Philippe Data Analytics Portfolio"
author: "Shey Jean-Philippe"
description: "Website to display my projects"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "SheyJean-Philippe Data Analytics Portfolio"}
  - {file: "index.html"}
  - {file: "README.md", title: "About me"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"}
  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/sheyjeanphilippe/"}
  - {title: Test, icon: mug-hot, url: ""}
  - {title: Test, icon: fa-regular fa-dragon, url: ""}
  - {title: Test, icon: dragon, url: ""}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
